<a href="https://colab.research.google.com/github/Kaiziferr/deep_learning/blob/master/Introduction_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.8.2'

# **Constant**
---

## **Define constant**
---

In [4]:
tensor = tf.constant([[23, 4], [32, 51]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
tensor.shape

TensorShape([2, 2])

## **Consult values of a constant**
---

In [6]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [7]:
# Convert an array to tensor
numpy_tensor = np.array([[23,4],[32,51]])

In [8]:
tensor_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# **Variables**
---

## **Define an variable**
---

In [12]:
tf_variable = tf.Variable([[1.,2.,3.], [4., 5., 6.,]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

## **Set value an variable**

In [15]:
tf_variable[0,2].assign(200)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 200.],
       [  4.,   5.,   6.]], dtype=float32)>

In [16]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 200.],
       [  4.,   5.,   6.]], dtype=float32)>

# **Operation**
---

In [17]:
tensor = tf.constant([[1,2], [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Sum

In [18]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

Multiplicar un escalar por un tensor

In [19]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [20]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [21]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

Producto escalar entre dos tensores

In [22]:
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]], dtype=int32)

# **String**
---

In [23]:
tf_string = tf.constant('Tensorflow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [26]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [27]:
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [28]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [29]:
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
